[package]
name = "cfgen"
version = "0.1.0"
authors = ["foldu <foldu@protonmail.com>"]
edition = "2018"
license = "MIT"

[features]
with-toml = ["cfgen_derive/with-toml", "toml"]
yaml = ["cfgen_derive/yaml", "serde_yaml"]

[dependencies]
cfgen_derive = { path = "cfgen_derive" }
lazy_static = "1.2.0"
directories = "1.0.2"
serde_yaml = { version = "0.8.8", optional = true }
toml = { version = "0.4.10", optional = true }

[dev-dependencies]
serde_derive = "1.0.87"
serde = "1.0.87"
